document.getElementById("action").addEventListener("click", function(){
	//Place your code between this comment
	var en = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
    var es = ["Domingo", "Lune", "Martes", "Miercoles", "Jueves", "Viernes", "Sabado"];
    var fr = ["Dimanche", "Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi","Samedi"];
    var pt = ["Domingo", "Segunda-feira", "Tercca-feira", "Quarta-feira", "Quinta-feria", "Sexta-feira", "Sabado"];
    
    var s = "<h2>These Are The Days Of The Weeks Translated</h2>";
        s += "<table>";
        s += "<tr>";
          s += "<th>" + en[0] +"</th>";
          s += "<th>" + en[1] +"</th>";
          s += "<th>" + en[2] +"</th>";
          s += "<th>" + en[3] +"</th>";
          s += "<th>" + en[4] +"</th>";
          s += "<th>" + en[5] +"</th>";
          s += "<th>" + en[6] +"</th>";  
        s += "</th>";
        s += "<tr>";
          s += "<td>Espanol (Spanish)</td>";
          s += "<td>" +es[0] + "</td>";
          s += "<td>" +es[1] + "</td>";
          s += "<td>" +es[2] + "</td>";
          s += "<td>" +es[3] + "</td>";
          s += "<td>" +es[4] + "</td>";
          s += "<td>" +es[5] + "</td>";
          s += "<td>" +es[6] + "</td>";
        s += "</tr>";
        s += "<tr>";
          s += "<td>Francais (Franch)</td>";
          s += "<td>" +fr[0] + "</td>";
          s += "<td>" +fr[1] + "</td>";
          s += "<td>" +fr[2] + "</td>";
          s += "<td>" +fr[3] + "</td>";
          s += "<td>" +fr[4] + "</td>";
          s += "<td>" +fr[5] + "</td>";
          s += "<td>" +fr[6] + "</td>";
        s += "</tr>";
        s += "<tr>";
          s += "<td>Portugues (Portguese)</td>";
          s += "<td>" +pt[0] + "</td>";
          s += "<td>" +pt[1] + "</td>";
          s += "<td>" +pt[2] + "</td>";
          s += "<td>" +pt[3] + "</td>";
          s += "<td>" +pt[4] + "</td>";
          s += "<td>" +pt[5] + "</td>";
          s += "<td>" +pt[6] + "</td>";
        s += "</tr>";
        s += "</table>";
	//And this comment
    document.getElementById("days-holder").innerHTML = s;
    var myArray = new Array();
    myArray.push(prompt("Let’s create our own language. What is the name of your new language?", "Nebraskan"));
    myArray.push(prompt("How do you say Sunday  in your language?", "Go Big Sunday"));
    myArray.push(prompt("How do you say Monday in your language?", "Go Big Monday"));
    myArray.push(prompt("How do you say Tuesday in your language?", "Go Big Tuesday"));
    myArray.push(prompt("How do you say Wednesday in your language?", "Go Big Wednesday"));
    myArray.push(prompt("How do you say Thursday in your language?", "Go Big Thursday"));
    myArray.push(prompt("How do you say Friday in your language?", "Go Big Friday"));
    myArray.push(prompt("How do you say Saturdayday in your language?", "Go Big Saturday"));
    var l = "<h2>These Are The Days Of The Weeks Translated Into" + myArray[0] +":</h2>";
      l += "<ol>";
        l += "<li>" + en[0] + "in" +myArray[0] +  "is" + "\"" +myArray[1] + "\"</li>";
        l += "<li>" + en[0] + "in" +myArray[1] +  "is" + "\"" +myArray[2] + "\"</li>";
        l += "<li>" + en[0] + "in" +myArray[2] +  "is" + "\"" +myArray[3] + "\"</li>";
        l += "<li>" + en[0] + "in" +myArray[3] +  "is" + "\"" +myArray[4] + "\"</li>";
        l += "<li>" + en[0] + "in" +myArray[4] +  "is" + "\"" +myArray[5] + "\"</li>";
        l += "<li>" + en[0] + "in" +myArray[5] +  "is" + "\"" +myArray[6] + "\"</li>";
        l += "<li>" + en[0] + "in" +myArray[6] +  "is" + "\"" +myArray[7] + "\"</li>";
      l += "</ol>";
    document.getElementById("days-holder-user").innerHTML = l;
});